### ISSUE TITLE
Question sometimes reveals answer when skips are enabled

### ISSUE THREAD

**Issue by justinkeung1018** [qbreader/website#295]
![image](https://github.com/qbreader/website/assets/94550621/3395f476-7d17-4261-b976-717688f4ff8f)
As seen in the screenshot, the answer and the whole question reveal themselves while it is supposed to still be reading "... bitten in the eye in the process of...". This happens sporadically when skips are enabled.

**Comment by BolunThompson** [comment]
With thanks to a member of my QB team, here's a more detailed description of the issue:

> If you open the settings tab, there's a timer on the side that starts counting down whenever you buzz in for a question. Once the timer runs out, it reveals whatever question you're on.
If you answer & skip before the timer runs out, then instead of resetting it just reveals the next question.
> To avoid this you'd have to wait until the timer runs out before skipping to the next question.
> If you wait for the timer to run out after answering, it inevitably marks your answer as wrong once it reaches 0.

![before](https://github.com/qbreader/website/assets/28687672/7377a909-1f0d-4594-9b8d-e0498256afa5)
![after](https://github.com/qbreader/website/assets/28687672/b93a2ef8-422e-4779-9ec7-51dc8418ecb6)

**Comment by PSlape2** [comment]
I believe the error is that the timer on line is not being ended when the player buzzes, so if the player moves to the next question before the timer ends, it continues running and preemptively ends the next question.

Timer:
https://github.com/qbreader/website/blob/00171fb287fd95ef0cc13050b6108fe189964913/client/singleplayer/tossups.js#L426
