### ISSUE TITLE
Difficulty and time selectors not appearing

### ISSUE THREAD

**Issue by Amekyras** [qbreader/website#323]
Issue: When loading into a new singleplayer or multiplayer room, the difficulty and year menus do not appear

Steps to reproduce: Go to site on desktop Chrome, open room

Notes: I've found that enabling then disabling the 'select by set name' option makes the menus reappear, maybe it's something playing up with the CSS?

**Comment by 1337isnot1337** [comment]
This is because you likely have the "select by set name" enabled by default (it might be stored in you cache/cookies/local storage). This is not a bug. With the "select by set name" option enabled users can choose to play with a specific set and its packets, and when it is enabled you thus cannot choose the difficulty/year (because one packet/packet set is one difficulty and all the same year). To play as normal with the categories and difficulty fields just disable the "select by set name" option and you should be good. Again, you might be able to clear cookies/cache/local storage to revert to the default of it being disabled.

**Comment by geoffrey-wu** [comment]
Ah, I think some other users are having a similar issue to this. I suspect the issue is not related to the above, but rather some issue with how the year ranges are loaded? Not sure why, but (only) sometimes jQuery complains when trying to set the values of the slider too early.
